/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Anh Thang' at '8/4/16 11:12 PM' with Gradle 2.13
 *
 * @author Anh Thang, @date 8/4/16 11:12 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
